spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${datasource.postgres.url}
    username: ${datasource.postgres.username}
    password: ${datasource.postgres.password}
  cassandra:
    contact-points: ${cass.contact-points}
    port: ${cass.port}
    localDatacenter: datacenter1
    keyspace-name: bank_currencies
    schema-action: CREATE_IF_NOT_EXISTS
    request.timeout: 10s
#      username: ${cassandra.username}
#      password: ${cassandra.password}
    connection: 
      connect-timeout: 10s
      init-query-timeout: 10s
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa: 
    show-sql: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
            format_sql: true
