spring:
  property: This the the application-test.yaml file
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    localDatacenter: datacenter1
    keyspace-name: spring_cassandra
    schema-action: CREATE_IF_NOT_EXISTS
    request.timeout: 10s
#    username: cassandra
#    password: cassandra
    connection: 
        connect-timeout: 10s
        init-query-timeout: 10s
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa: 
    show-sql: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
            format_sql: true
my.var: Hello world
#new.var: ${my.properties}
