spring:
  datasource:
    postgres:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.20.10.2:6432/bank
        username: postgres
        password: postgres
#  data:
#    cassandra:
#        schema-action: CREATE_IF_NOT_EXISTS
#        request:
#            timeout: 10s
#        connection:
#            connect-timeout: 10s
#            init-query-timeout: 10s
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa: 
    show-sql: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
            format_sql: true